image:
  file: .gitpod.dockerfile
tasks:
  - name: shell
    command: nix-shell
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: false
    # add a check to pull requests (defaults to true)
    addCheck: false
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true

vscode:
  extensions:
    - bbenoist.Nix@1.0.1:TbrU16w37jLfkqA6h20vuQ==
    - EditorConfig.EditorConfig@0.15.1:wTLttUDotgRJ2XHnXVuC0A==
    - CoenraadS.bracket-pair-colorizer@1.0.61:fqPT1sJEqaEdrfXeYbdW+A==